//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NifrekaNetTraffic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NifrekaNetTraffic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the Log file?.
        /// </summary>
        public static string Dialog_ClearLog_Question {
            get {
                return ResourceManager.GetString("Dialog_ClearLog_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string DialogMissingFile_button_quit {
            get {
                return ResourceManager.GetString("DialogMissingFile_button_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following file is missing:.
        /// </summary>
        public static string DialogMissingFile_file_missing {
            get {
                return ResourceManager.GetString("DialogMissingFile_file_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files are missing:.
        /// </summary>
        public static string DialogMissingFile_files_missing {
            get {
                return ResourceManager.GetString("DialogMissingFile_files_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NifrekaNetTraffic.
        /// </summary>
        public static string dlgAbout_Title {
            get {
                return ResourceManager.GetString("dlgAbout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version of NifrekaNetTraffic is available..
        /// </summary>
        public static string dlgNewVersion_1_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_1_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed version:.
        /// </summary>
        public static string dlgNewVersion_2_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_2_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.000.
        /// </summary>
        public static string dlgNewVersion_3_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_3_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version:.
        /// </summary>
        public static string dlgNewVersion_4_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_4_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.000.
        /// </summary>
        public static string dlgNewVersion_5_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_5_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recomended that you update to the new version now..
        /// </summary>
        public static string dlgNewVersion_6_YesNo {
            get {
                return ResourceManager.GetString("dlgNewVersion_6_YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string dlgNewVersion_7_YesNo_Later {
            get {
                return ResourceManager.GetString("dlgNewVersion_7_YesNo_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        public static string dlgNewVersion_8_YesNo_Now {
            get {
                return ResourceManager.GetString("dlgNewVersion_8_YesNo_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dlgYesNo_Cancel {
            get {
                return ResourceManager.GetString("dlgYesNo_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dlgYesNo_OK {
            get {
                return ResourceManager.GetString("dlgYesNo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NifrekaNetTraffic-ReadMe.rtf.
        /// </summary>
        public static string filename_Readme_rtf {
            get {
                return ResourceManager.GetString("filename_Readme_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CapsLock.
        /// </summary>
        public static string label_CapsLock {
            get {
                return ResourceManager.GetString("label_CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumLock.
        /// </summary>
        public static string label_NumLock {
            get {
                return ResourceManager.GetString("label_NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrollLock.
        /// </summary>
        public static string label_ScrollLock {
            get {
                return ResourceManager.GetString("label_ScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About NifrekaNetTraffic....
        /// </summary>
        public static string main_context_About {
            get {
                return ResourceManager.GetString("main_context_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string main_context_Close {
            get {
                return ResourceManager.GetString("main_context_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Layout.
        /// </summary>
        public static string main_context_DefaultLayout {
            get {
                return ResourceManager.GetString("main_context_DefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto NifrekaNetTraffic Webpage.
        /// </summary>
        public static string main_context_GotoHomePage {
            get {
                return ResourceManager.GetString("main_context_GotoHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Graph.
        /// </summary>
        public static string main_context_OpenGraph {
            get {
                return ResourceManager.GetString("main_context_OpenGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Readme.
        /// </summary>
        public static string main_context_OpenReadme {
            get {
                return ResourceManager.GetString("main_context_OpenReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Table.
        /// </summary>
        public static string main_context_OpenTable {
            get {
                return ResourceManager.GetString("main_context_OpenTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topmost.
        /// </summary>
        public static string main_context_Topmost {
            get {
                return ResourceManager.GetString("main_context_Topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string text_off {
            get {
                return ResourceManager.GetString("text_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string toolTip_Received {
            get {
                return ResourceManager.GetString("toolTip_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string toolTip_Sent {
            get {
                return ResourceManager.GetString("toolTip_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/s.
        /// </summary>
        public static string wind_graph_bytesPerSecond {
            get {
                return ResourceManager.GetString("wind_graph_bytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string wind_graph_EndOffset {
            get {
                return ResourceManager.GetString("wind_graph_EndOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Max:.
        /// </summary>
        public static string wind_graph_ReceivedMax {
            get {
                return ResourceManager.GetString("wind_graph_ReceivedMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Max:.
        /// </summary>
        public static string wind_graph_SentMax {
            get {
                return ResourceManager.GetString("wind_graph_SentMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string wind_graph_StartOffset {
            get {
                return ResourceManager.GetString("wind_graph_StartOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NifrekaNetTraffic - ReadMe.
        /// </summary>
        public static string wind_ReadMe_Title {
            get {
                return ResourceManager.GetString("wind_ReadMe_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoScroll.
        /// </summary>
        public static string wind_table_AutoScroll {
            get {
                return ResourceManager.GetString("wind_table_AutoScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count:.
        /// </summary>
        public static string wind_table_Count {
            get {
                return ResourceManager.GetString("wind_table_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date - Time.
        /// </summary>
        public static string wind_table_DateTime {
            get {
                return ResourceManager.GetString("wind_table_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string wind_table_Interval {
            get {
                return ResourceManager.GetString("wind_table_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received [B].
        /// </summary>
        public static string wind_table_ReceivedBytes {
            get {
                return ResourceManager.GetString("wind_table_ReceivedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent[B].
        /// </summary>
        public static string wind_table_SentBytes {
            get {
                return ResourceManager.GetString("wind_table_SentBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string Window_Position_BottomLeft {
            get {
                return ResourceManager.GetString("Window_Position_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string Window_Position_BottomRight {
            get {
                return ResourceManager.GetString("Window_Position_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string Window_Position_TopLeft {
            get {
                return ResourceManager.GetString("Window_Position_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string Window_Position_TopRight {
            get {
                return ResourceManager.GetString("Window_Position_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Layout.
        /// </summary>
        public static string WindowLog_context_DefaultLayout {
            get {
                return ResourceManager.GetString("WindowLog_context_DefaultLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Logs.
        /// </summary>
        public static string WindowLog_context_SyncLogs {
            get {
                return ResourceManager.GetString("WindowLog_context_SyncLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause display.
        /// </summary>
        public static string WindowLogGraph_context_Pause {
            get {
                return ResourceManager.GetString("WindowLogGraph_context_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string WindowLogTable_ClearLog {
            get {
                return ResourceManager.GetString("WindowLogTable_ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as Text.
        /// </summary>
        public static string WindowLogTable_ExportAsText {
            get {
                return ResourceManager.GetString("WindowLogTable_ExportAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log total-&gt;.
        /// </summary>
        public static string WindowLogTable_Log {
            get {
                return ResourceManager.GetString("WindowLogTable_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NetworkInterface.
        /// </summary>
        public static string WindowLogTable_NetworkInterface {
            get {
                return ResourceManager.GetString("WindowLogTable_NetworkInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Directory.
        /// </summary>
        public static string WindowLogTable_OpenLogDir {
            get {
                return ResourceManager.GetString("WindowLogTable_OpenLogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection -&gt;.
        /// </summary>
        public static string WindowLogTable_Selection {
            get {
                return ResourceManager.GetString("WindowLogTable_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since activated-&gt;.
        /// </summary>
        public static string WindowLogTable_Total {
            get {
                return ResourceManager.GetString("WindowLogTable_Total", resourceCulture);
            }
        }
    }
}
